// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIwvMQrsexWyUgi7kStviKCvhFMgD2j2A',
    appId: '1:810603844910:web:a497269953af73ced996bf',
    messagingSenderId: '810603844910',
    projectId: 'nellweather',
    authDomain: 'nellweather.firebaseapp.com',
    storageBucket: 'nellweather.firebasestorage.app',
    measurementId: 'G-56DXMTTXPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YoR_7OHLs8A8YS7jJr1Lj9kqwk41emg',
    appId: '1:810603844910:android:0af59b4f8dfdd29ed996bf',
    messagingSenderId: '810603844910',
    projectId: 'nellweather',
    storageBucket: 'nellweather.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJmYxhJ2dM_xRG4k6nScEDFv5NA1ApSk',
    appId: '1:810603844910:ios:bf0aef1ef33e5e4ad996bf',
    messagingSenderId: '810603844910',
    projectId: 'nellweather',
    storageBucket: 'nellweather.firebasestorage.app',
    iosClientId: '810603844910-cb2qenu89ggvklba78fk9006t95333v0.apps.googleusercontent.com',
    iosBundleId: 'com.reha.nellweather',
  );
}
