class GeoPoint {
  final double lat; // 위도
  final double lon; // 경도

  const GeoPoint(this.lat, this.lon);
}

enum BirthPlaceCode {
  seoul,
  busan,
  daegu,
  incheon,
  gwangju,
  daejeon,
  ulsan,
  sejong,
  suwon,
  jeju,
  // 계속 확장
}

const Map<BirthPlaceCode, GeoPoint> birthPlaceGeoMap = {
  BirthPlaceCode.seoul: GeoPoint(37.566535, 126.977969),
  BirthPlaceCode.busan: GeoPoint(35.179554, 129.075642),
  BirthPlaceCode.daegu: GeoPoint(35.871435, 128.601445),
  BirthPlaceCode.incheon: GeoPoint(37.456256, 126.705206),
  BirthPlaceCode.gwangju: GeoPoint(35.159545, 126.852601),
  BirthPlaceCode.daejeon: GeoPoint(36.350412, 127.384548),
  BirthPlaceCode.ulsan: GeoPoint(35.538377, 129.311359),
  BirthPlaceCode.sejong: GeoPoint(36.480098, 127.289035),
  BirthPlaceCode.suwon: GeoPoint(37.263573, 127.028601),
  BirthPlaceCode.jeju: GeoPoint(33.499621, 126.531188),
};

const Map<BirthPlaceCode, String> birthPlaceDisplayKo = {
  BirthPlaceCode.seoul: '서울특별시, 대한민국',
  BirthPlaceCode.busan: '부산광역시, 대한민국',
  BirthPlaceCode.daegu: '대구광역시, 대한민국',
  BirthPlaceCode.incheon: '인천광역시, 대한민국',
  BirthPlaceCode.gwangju: '광주광역시, 대한민국',
  BirthPlaceCode.daejeon: '대전광역시, 대한민국',
  BirthPlaceCode.ulsan: '울산광역시, 대한민국',
  BirthPlaceCode.sejong: '세종특별자치시, 대한민국',
  BirthPlaceCode.suwon: '경기도 수원시, 대한민국',
  BirthPlaceCode.jeju: '제주특별자치도 제주시, 대한민국',
};

const List<String> worldCityKo = [
  // 한국
  '서울특별시, 대한민국',
  '울산광역시, 대한민국',
  '대전광역시, 대한민국',
  '경기도 수원시, 대한민국',
  '인천광역시, 대한민국',
  '대구광역시, 대한민국',
  '부산광역시, 대한민국',
  '경상남도 창원시, 대한민국',
  '광주광역시, 대한민국',
  '강원도 춘천시, 대한민국',
  '전라북도 전주시, 대한민국',
  '제주특별자치도 제주시, 대한민국',
  '충청북도 청주시, 대한민국',
  '경상북도 안동, 대한민국',
  '세종특별자치시 世宗, 대한민국',
  '전라남도 Muan, 대한민국',
  '충청남도 Hongseong, 대한민국',
  '경기도 고양시, 대한민국',
  '경상남도 양산, 대한민국',
  '전라남도 순천, 대한민국',
  '전라남도 여수, 대한민국',
  '경상북도 포항, 대한민국',
  '전라남도 목포, 대한민국',
  '경상북도 경산시, 대한민국',
  '경상북도 龜尾市, 대한민국',
  '충청남도 보령, 대한민국',
  '강원도 속초, 대한민국',
  '전라남도 광양, 대한민국',
  '전라남도 나주, 대한민국',
  '전라남도 화순, 대한민국',
  '전라남도 영암, 대한민국',
  '경상남도 하동, 대한민국',
  '경상북도 예천, 대한민국',
  '전라남도 담양, 대한민국',
  '충청남도 Buyeo, 대한민국',
  '전라남도 장성, 대한민국',
  '전라남도 장흥, 대한민국',
  '강원도 화천군, 대한민국',
  '전라남도 보성, 대한민국',
  '충청북도 Yeongdong, 대한민국',
  '경기도 부천시, 대한민국',
  '경기도 성남시, 대한민국',
  '충청남도 天安市, 대한민국',
  '경기도 오산시, 대한민국',
  '경기도 안산시, 대한민국',
  '경상남도 김해시, 대한민국',
  '경기도 연천, 대한민국',
  '경기도 법원, 대한민국',
  '부산광역시 동래, 대한민국',
  '충청북도 충주, 대한민국',
  '경상남도 진주시, 대한민국',
  '경상북도 경주시, 대한민국',
  '전라북도 군산시, 대한민국',
  '경상북도 김천, 대한민국',
  '전라북도 익산시, 대한민국',
  '경상북도 영덕, 대한민국',
  '경기도 양주, 대한민국',
  '강원도 원주시, 대한민국',
  '경기도 안양시, 대한민국',
  '경기도 구리시, 대한민국',
  '경기도 Gunpo, 대한민국',
  '경기도 이천시, 대한민국',
  '경기도 화성시, 대한민국',
  '경기도 하남, 대한민국',
  '충청남도 아산, 대한민국',
  '경기도 Yangp\'yŏng, 대한민국',
  '경상북도 Sangju, 대한민국',
  '경기도 평택시, 대한민국',
  '경기도 안성시, 대한민국',
  '경상남도 밀양시, 대한민국',
  '경기도 광주시, 대한민국',
  '경기도 Gapyeong, 대한민국',
  '강원도 Donghae City, 대한민국',
  '경기도 남양주시, 대한민국',
  '경기도 의정부시, 대한민국',
  '광주광역시 마산, 대한민국',
  '제주특별자치도 Seogwipo, 대한민국',
  '충청남도 서산시, 대한민국',
  '전라북도 Nangen, 대한민국',
  '경상북도 문경, 대한민국',
  '전라북도 정읍시, 대한민국',
  '대전광역시 Yuseong, 대한민국',
  '충청남도 공주시, 대한민국',
  '경기도 광명, 대한민국',
  '경기도 驪州市, 대한민국',
  '강원도 Kosong, 대한민국',
  '강원도 홍천군, 대한민국',
  '경상남도 Sinhyeon, 대한민국',
  '경기도 Hwado, 대한민국',
  '충청남도 Cheongyang, 대한민국',
  '전라북도 완주, 대한민국',
  '강원도 Santyoku, 대한민국',
  '경상남도 Goseong, 대한민국',
  '경상남도 Kyosai, 대한민국',
  '경상남도 창녕, 대한민국',
  '경상북도 영주, 대한민국',
  '강원도 평창군, 대한민국',
  '충청남도 논산시, 대한민국',
  '전라남도 Kwangyang, 대한민국',
  '전라북도 고창, 대한민국',

  // 일본
  '도쿄',
  '오사카',
  '교토',

  // 중국
  '베이징',
  '상하이',
  '광저우',

  // 미국
  '뉴욕',
  '로스앤젤레스',
  '샌프란시스코',

  // 유럽
  '런던',
  '파리',
  '베를린',
];
